name: Android

on:
  push:
    branches:
      - master

jobs:
  build-android:
    name: build-android
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Run build script
        run: |
          cd build/android && ./build.sh continuous
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-android
          path: out/*.aar
