name: Presubmit

on: [pull_request]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Test Python
        run: |
          python --version
          pip install PyGithub
          python -c "import github"

  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Test Python
        run: |
          python --version
          pip install PyGithub
          python -c "import github"
        shell: bash
