name: Release

on:
  release:
    types: [created]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/bejado/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          WORKFLOW_OS=`echo \`uname\` | sed "s/Darwin/mac/" | tr [:upper:] [:lower:]`
          cd build/$WORKFLOW_OS && ./build.sh release
      - name: Upload release artifacts
        run: |
          WORKFLOW_OS=`echo \`uname\` | sed "s/Darwin/mac/" | tr [:upper:] [:lower:]`
          pip3 install setuptools
          pip3 install PyGithub
          TAG_NAME=${GITHUB_REF##*/}
          python3 build/common/upload-artifacts.py ${TAG_NAME} out/*.tgz out/*.aar
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}

  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/bejado/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
        shell: bash
      - name: Upload test artifact
        run: |
          echo "Hello, world" > test-windows.txt
          pip3 install PyGithub
          TAG_NAME=${GITHUB_REF##*/}
          python build/common/upload-artifacts.py ${TAG_NAME} test-windows.txt
        shell: bash
        env:
          GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
