name: Release

# This Workflow can be triggered two ways:
# 1. A GitHub release is created (using the GitHub web UI). This triggers all of the platforms to
# build and upload assets.
# 2. A workflow_dispatch event is triggered from the GitHub web UI. This triggers a build for only
# the platform specified in the dispatch event.

env:
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}

# The default GITHUB_TOKEN does not have write permissions, which is needed to upload release
# assets.
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build (desktop, web, android, ios, windows)'
        required: true
        default: 'desktop'
      release_tag:
        description: 'Release tag to build (e.g., v1.13.0)'
        required: true
        default: 'v1.13.0'
  release:
    types: [created]

jobs:
  build-android:
    name: build-android
    runs-on: 'ubuntu-latest'
    if: github.event_name == 'release' || github.event.inputs.platform == 'android'

    steps:
      - name: Decide Git ref
        id: git_ref
        run: |
          REF=${RELEASE_TAG:-${GITHUB_REF}}
          TAG=${REF##*/}
          echo "ref=${REF}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4.1.6
        with:
          ref: ${{ steps.git_ref.outputs.ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ./.github/actions/linux-prereq
      - name: Run build script
        env:
          TAG: ${{ steps.git_ref.outputs.tag }}
        run: |
          cd build/android && printf "y" | ./build.sh release arm64-v8a
          cd ../..
          mv out/filament-android-release.aar out/filament-${TAG}-android.aar
          mv out/filamat-android-release.aar out/filamat-${TAG}-android.aar
          mv out/gltfio-android-release.aar out/gltfio-${TAG}-android.aar
          mv out/filament-utils-android-release.aar out/filament-utils-${TAG}-android.aar
          mv out/filament-android-release-linux.tgz out/filament-${TAG}-android-native.tgz
      - uses: actions/github-script@v6
        env:
          TAG: ${{ steps.git_ref.outputs.tag }}
        with:
          script: |
            const upload = require('./build/common/upload-release-assets');
            const { TAG } = process.env;
            const globber = await glob.create(['out/*.aar', 'out/*.apk', 'out/*.tgz'].join('\n'));
            await upload({ github, context }, await globber.glob(), TAG);

  sonatype-publish:
    name: sonatype-publish
    runs-on: 'ubuntu-latest'
    needs: build-android
    if: github.event_name == 'release' || github.event.inputs.platform == 'android'

    steps:
      - name: Decide Git ref
        id: git_ref
        run: |
          REF=${RELEASE_TAG:-${GITHUB_REF}}
          TAG=${REF##*/}
          echo "ref=${REF}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4.1.6
        with:
          ref: ${{ steps.git_ref.outputs.ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ./.github/actions/linux-prereq
      - name: Download Android Release
        run: |
          gh release download ${TAG} \
            --repo ${{ github.repository }} \
            --pattern 'filament-*-android-native.tgz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Unzip Android Release
        run: |
          mkdir -p out/android-release
          tar -xzvf filament-*-android-release-native.tgz -C out/android-release/
      - name: Publish To Sonatype
        run: |
          cd android
          ./gradlew -Pcom.google.android.filament.abis=arm64-v8a publishToSonatype closeSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD }}

