name: Release

# This Workflow can be triggered two ways:
# 1. A GitHub release is created (using the GitHub web UI). This triggers all of the platforms to
# build and upload assets.
# 2. A workflow_dispatch event is triggered from the GitHub web UI. This triggers a build for only
# the platform specified in the dispatch event.

env:
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build (desktop, web, android, ios, windows)'
        required: true
        default: 'desktop'
      release_tag:
        description: 'Release tag to build (e.g., v1.13.0)'
        required: true
        default: 'v1.13.0'
  release:
    types: [created]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'release' || github.event.inputs.platform == 'desktop'

    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]

    steps:
      - name: Decide Git ref
        id: git_ref
        run: |
          REF=${RELEASE_TAG:-${GITHUB_REF}}
          TAG=${REF##*/}
          echo ::set-output name=ref::${REF}
          echo ::set-output name=tag::${TAG}
      - uses: actions/checkout@v2.0.0
        with:
          ref: ${{ steps.git_ref.outputs.ref }}
      - name: Run build script
        run: |
          mkdir -p out
          WORKFLOW_OS=`echo \`uname\` | sed "s/Darwin/mac/" | tr [:upper:] [:lower:]`
          echo "Hello world" > out/filament-${WORKFLOW_OS}.txt
          if [ -f out/filament-release-darwin.tgz ]; then mv out/filament-release-darwin.tgz out/filament-${TAG}-mac.tgz; fi;
          if [ -f out/filament-release-linux.tgz ]; then mv out/filament-release-linux.tgz out/filament-${TAG}-linux.tgz; fi;
      - uses: actions/github-script@v6
        env:
          TAG: '${{process.TAG}}'
        with:
          script: |
            const upload = require('./upload-release-assets.js');
            const { TAG } = process.env;
            const globber = await glob.create('out/*.txt');
            await upload({ github, context }, await globber.glob(), TAG);